      
apiVersion: v1
kind: Namespace
metadata:
  name: dify
---
# Dify Credentials PostgreSQL(reference with the cloud sql)
apiVersion: v1
kind: Secret
metadata:
  name: dify-credentials-postgresql
  namespace: dify
data:
  DB_DATABASE: ZGlmeQ==
  DB_HOST: cG9zdGdyZXM0OTk4ZWYxYzNlMTEucmRzLXBnLml2b2xjZXMuY29t
  DB_PASSWORD: RGVtb0A2NjY=
  DB_PORT: NTQzMg==
  DB_USERNAME: a3lsaW4=
type: Opaque
---
# Dify Credentials Redis(reference with the cloud redis)
apiVersion: v1
kind: Secret
metadata:
  name: dify-credentials-redis
  namespace: dify
data:
  REDIS_HOST: cmVkaXMtY25sZjN1cHVlcTdvd3Jrb3oucmVkaXMuaXZvbGNlcy5jb20=
  REDIS_PASSWORD: RGVtb0A2NjY=
  REDIS_PORT: NjM3OQ==
  REDIS_USERNAME: a3lsaW4=
type: Opaque
---
# Dify Credentials
apiVersion: v1
kind: Secret
metadata:
  name: dify-credentials
  namespace: dify
data:
  # Base64 encoded weaviate host, default is dify-weaviate
  weaviate-host: ZGlmeS13ZWF2aWF0ZQ==
  # Base64 encoded weaviate port 8080
  weaviate-port: ODA4MA==
type: Opaque

# Weaviate Server Start
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: dify-weaviate
  name: dify-weaviate
  namespace: dify
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/instance: dify-weaviate
  name: dify-weaviate
  namespace: dify
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: dify-weaviate
  name: dify-weaviate
  namespace: dify
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dify-weaviate
subjects:
- kind: ServiceAccount
  name: dify-weaviate
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dify-weaviate
  namespace: dify
spec:
  selector:
    matchLabels:
      app: dify-weaviate
  serviceName: "dify-weaviate"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: dify-weaviate
    spec:
      terminationGracePeriodSeconds: 10
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: dify-weaviate
      volumes:
      - name: weaviate-data
        hostPath:
          path: /root/dify/db/weaviate/data
          type: DirectoryOrCreate
      containers:
      - name: dify-weaviate
        image: dify-cn-beijing.cr.volces.com/dify/semitechnologies/weaviate:1.19.0
        ports:
        - containerPort: 8080
          name: weaviate-p
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 102Mi
        env:
        - name: QUERY_DEFAULTS_LIMIT
          value: "25"
        - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
          value: "false"
        - name: PERSISTENCE_DATA_PATH
          value: "/var/lib/weaviate"
        - name: "DEFAULT_VECTORIZER_MODULE"
          value: "none"
        - name: "AUTHENTICATION_APIKEY_ENABLED"
          value: "true"
        - name: "AUTHENTICATION_APIKEY_ALLOWED_KEYS"
          value: "WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih"
        - name: "AUTHENTICATION_APIKEY_USERS"
          value: "hello@dify.ai"
        - name: "AUTHORIZATION_ADMINLIST_ENABLED"
          value: "true"
        - name: "AUTHORIZATION_ADMINLIST_USERS"
          value: "hello@dify.ai"
        volumeMounts:
        - name: weaviate-data
          mountPath: /var/lib/weaviate
---
apiVersion: v1
kind: Service
metadata:
  name: dify-weaviate
  namespace: dify
spec:
  selector:
    app: dify-weaviate
  type: ClusterIP
  clusterIP: None
  ports:
  - name: weaviate
    protocol: TCP
    port: 8080
    targetPort: 8080
# Weaviate Server End

