apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: doubao
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: cr.volces.com/poc/ui:0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4000
        env:
        - name: BACKEND_API_HOST
          value: na
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: ui-svc
  namespace: doubao
spec:
  ports:
  - name: ui-svc
    port: 80
    protocol: TCP
    targetPort: 4000
  selector:
    app: ui
  type: ClusterIP


