= ADK
:toc: manual

== Concepts

=== What Developer really want?

To give developers a powerful, open foundation for building complex, production-ready AI agents intuitively and with greater control.


Open Foundation:

* Model Agnostic: Doubao, Gemini
* Deployment Agnostic: VKE, Google Cloud
* Interoperability: Easy to integrate with any framework

=== Agent Development Kit

https://google.github.io/adk-docs/

Agent Development Kit (ADK) is a flexible and modular framework for developing and deploying AI agents. While optimized for Gemini and the Google ecosystem, ADK is model-agnostic, deployment-agnostic, and is built for compatibility with other frameworks. ADK was designed to make agent development feel more like software development, to make it easier for developers to create, deploy, and orchestrate agentic architectures that range from simple tasks to complex workflows.


Agent Development Kit offers several key advantages for developers building agentic applications:

1. Multi-Agent Systems: Build modular and scalable applications by composing multiple specialized agents in a hierarchy. Enable complex coordination and delegation.
2. Rich Tool Ecosystem: Equip agents with diverse capabilities: use pre-built tools (Search, Code Execution, etc.), create custom functions, integrate tools from third-party agent frameworks (LangChain, CrewAI), or even use other agents as tools.
3. Flexible Orchestration: Define workflows using workflow agents (SequentialAgent, ParallelAgent, and LoopAgent) for predictable pipelines, or leverage LLM-driven dynamic routing (LlmAgent transfer) for adaptive behavior.
4. Integrated Developer Experience: Develop, test, and debug locally with a powerful CLI and an interactive dev UI. Inspect events, state, and agent execution step-by-step.
5. Built-in Evaluation: Systematically assess agent performance by evaluating both the final response quality and the step-by-step execution trajectory against predefined test cases.
6. Deployment Ready: Containerize and deploy your agents anywhere – run locally, scale with Vertex AI Agent Engine, or integrate into custom infrastructure using Cloud Run or Docker.

Google ADK is built around a few core concepts that make it powerful and flexible:

* Agent: Agents are core building blocks designed to accomplish specific tasks. They can be powered by LLMs to reason, plan, and utilize tools to achieve goals, and can even collaborate on complex projects.
* Tools: Tools give agents abilities beyond conversation, letting them interact with external APIs, search information, run code, or call other services.
* Session Services: Session services handle the context of a single conversation (Session), including its history (Events) and the agent's working memory for that conversation (State).
* Callbacks: Custom code snippets you provide to run at specific points in the agent's process, allowing for checks, logging, or behavior modifications.
* Artifact Management: Artifacts allow agents to save, load, and manage files or binary data (like images or PDFs) associated with a session or user.
* Runner: The engine that manages the execution flow, orchestrates agent interactions based on Events, and coordinates with backend services.


== Development Environment

=== Python

[source,bash]
----
uv venv --python 3.12
source .venv/bin/activate
uv pip install google-adk
uv pip install veadk-python
----

=== Mysql

[source, bash]
----
docker run -d \
  --name mysql \
  -e MYSQL_ROOT_PASSWORD=root \
  -p 3306:3306 \
  mysql:8.0
----

[source, bash]
----
docker exec -it mysql bash
mysql -uroot -p
----

[source, bash]
----
CREATE DATABASE VEADK;
USE VEADK;
SHOW TABLES;
----

== Getting Start

=== my_agent

[source, bash]
.*1. create project*
----
adk create my_agent
----

*2. update code*

link:my_agent/agent.py[agent.py]

[source, bash]
.*3. run agent*
----
veadk web
----

[source, bash]
.*4. Run Agent CLI*
----
python my_agent/agent.py
----

=== web_search_agent 

[source, bash]
----
web_search_agent/agent.py
----

=== terminal_agent

[source, bash]
.*ShortTermMemory Local File*
----
python terminal_agent/short_mem_local_agent.py
----

[source, bash]
.*ShortTermMemory Mysql*
----
python terminal_agent/short_mem_mysql_agent.py
----

[source, bash]
.*LongTermMemory Opensearch*
----
python terminal_agent/long_mem_opensearch_agent.py
----

[source, bash]
.*LongTermMemory Viking*
----
terminal_agent/long_mem_viking_agent.py
----

=== intent_recognition_agent

[source, bash]
----
python intent_recognition_agent/agent.py 
----

